version: '3.9'

services:
  db:
    image: postgres:16.1-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagelite
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:8.1
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - '15432:80'
    depends_on:
      - db


